baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Omaha Symphonic Chorus"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
    tagline = "Omaha's premier large choral ensemble"